version: '2'
services:
  traefik:
    image: traefik:1.5.4
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - <INSERT ABSOLUTE PATH>/dns-ip-updater/server/traefik.toml:/traefik.toml
      - <INSERT ABSOLUTE PATH>/dns-ip-updater/server/acme.json:/acme.json
    container_name: traefik
  dius:
    image: <YOUR REGISTRY>/dns-ip-updater:server
    restart: always
    container_name: dns-ip-updater-server
    environment:
      - KEY=<your_security_key>
    networks:
      - web
      - default
    expose:
      - "8080"  
    labels:
      - "traefik.backend=<BACKEND ex: dns>"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:<DNS RECORD ex: dns.google.com>"
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.frontend.auth.basic=<encrypted_login_information>" 
networks:
  web:
    external: true


